### ISSUE TITLE
Необходимо продумать архитектуру и функционал

### ISSUE THREAD

**Issue by VasilyLapinsky** [sergeykoryagin/bank#2]
### Не забыть расписать все и завести и распределить задачи с получившейся архитектурой

**Comment by ch1cly** [comment]
https://www.figma.com/file/9Dbd8N59oVK8wCpwnZFwcH/Untitled?node-id=1%3A3427
![photo_2022-02-21 15 23 20](https://user-images.githubusercontent.com/57445583/154954975-87acceb5-25cf-4541-8171-b1e36638211d.jpeg)
![photo_2022-02-21 15 23 17](https://user-images.githubusercontent.com/57445583/154954989-c9af0cb6-9c24-453d-8f54-467e4a4ff60e.jpeg)
![photo_2022-02-21 15 23 26](https://user-images.githubusercontent.com/57445583/154954996-886c99b7-96a9-4073-ad8b-94b30cf5e2be.jpeg)
![photo_2022-02-21 15 23 28](https://user-images.githubusercontent.com/57445583/154955007-868ced7c-6c6d-49cd-aec1-4aab0634492c.jpeg)
![photo_2022-02-21 15 23 29](https://user-images.githubusercontent.com/57445583/154955019-630c58f0-77ff-4065-90fd-b74b9ab54f6d.jpeg)
