### ISSUE TITLE
Подобрать 16 максимально непохожих друг на друга цветов в формате hex. АНТОХА!!

### ISSUE THREAD

**Issue by ch1cly** [sergeykoryagin/bank#31]
Ответ впиши в ответе просто вставь типо #ff0000 но чтобы они норм вписывались в приложение

**Comment by rizzleduq** [comment]
#E20000 #F59421 #F5ED21 #00FF66 #00A3FF #0038FF #A400DE #004933 #00FFE0 #989898 #000000 #FF53C5 #993C07 #0E6E7B #6A0000 #979100
